### ISSUE TITLE
Обновление зависимостей

### ISSUE THREAD

**Issue by sollidy** [atls/common#6]
### С чем связан запрос на фичу?

Обновление зависимостей в репозитории

### Расскажите как вы это себе видите

После обновления должны корректно отрабатывать следующие команды:
- yarn check

### Приложите пример реализаций

- [Upgrade Interactive](https://classic.yarnpkg.com/lang/en/docs/cli/upgrade-interactive/)

**Comment by LevKrestuaninov** [comment]
## Не понимаю почему yarn не может получить доступ к node:fs
![Снимок экрана от 2023-08-07 12-22-38](https://github.com/atls/common/assets/126339170/dfd2cbe1-591d-4f9f-8ee3-80e09fc928b7)
![Снимок экрана от 2023-08-07 12-23-49](https://github.com/atls/common/assets/126339170/e1c57da5-2491-4909-884c-b8e1964d30d7)

**Comment by LevKrestuaninov** [comment]
![Снимок экрана от 2023-08-07 12-39-09](https://github.com/atls/common/assets/126339170/0de780ee-fc7b-4ea4-99e1-9f1455cc1f41)

**Comment by sollidy** [comment]
@LevKrestuaninov версия ноды должна быть минимум 18. Я бы рекомендовал для работы с нодой использовать nvm менеджер. Попробуй его установить и с его помощью установить уже node.js 
- https://github.com/nvm-sh/nvm

**Comment by LevKrestuaninov** [comment]
@sollidy  Выполнил на локальном уровне. Могу ли коммитить?
![image](https://github.com/atls/common/assets/126339170/ad517880-b58d-4f1b-9b51-480b807c3e8b)

**Comment by sollidy** [comment]
@LevKrestuaninov
- yarn test unit проходит?
- если чек не проходит, значит конфликты типов в новых библиотеках, попробуй их решить
- если мажорные версии не будут вставать, тогда уже минорное обновление
- создавай ветку, коммить

**Comment by sollidy** [comment]
@LevKrestuaninov для начала прочитай конвенцию как работать с gitHub:
- https://github.com/atls/convention
в ветку master мы ничего не пушим, только через новые ветки

**Comment by LevKrestuaninov** [comment]
@sollidy, создал ветку, запушил изменения, все тесты проходит

**Comment by sollidy** [comment]
@LevKrestuaninov хорошо, но тебе надо попробовать обновить все пакеты, кроме двух: 
- typescript: 4.9.5 - оставить
-  typeorm: "^0.2.45 - оставить
после обновления  jest у тебя будут ошибки в типизации тестов, нужно в них разобраться

**Comment by LevKrestuaninov** [comment]
@sollidy При обновлении typescript до 4.9.5 yarn check выдает ошибки  _logger/src/_ и _typeorm-logger/src/_ :
![Снимок экрана от 2023-08-07 17-53-20](https://github.com/atls/common/assets/126339170/5de3c84d-a027-443e-aa7e-9f714219b8d0)
после выполнения подсказки выдает такое: 
![Снимок экрана от 2023-08-07 17-54-22](https://github.com/atls/common/assets/126339170/d0c038eb-2ebf-4d45-830c-0336bad79b46)
Пробовал через yarn по советам в гугле, после выполнения ничего не меняется.
![Снимок экрана от 2023-08-07 17-55-23](https://github.com/atls/common/assets/126339170/5b4cf4bd-8aba-4142-a8f0-478cf6fd84e6)

**Comment by sollidy** [comment]
На обновлении какого конкретного пакета выходят ошибки?

**Comment by LevKrestuaninov** [comment]
обновление _jest/core_ и _types/jest_ не выдает ошибок

**Comment by sollidy** [comment]
> На обновлении какого конкретного пакета выходят ошибки?

?

**Comment by sollidy** [comment]
попробуй по одному пакету обновлять и делать проверки

**Comment by LevKrestuaninov** [comment]
typescript до версии 4.9.5

**Comment by LevKrestuaninov** [comment]
я так и делал, по одному пакету

**Comment by LevKrestuaninov** [comment]
eslint, typescript выдает ошибки
в eslint еще не разбирался с ошибками, ts не понимаю

**Comment by LevKrestuaninov** [comment]
на данный момент из возможных обновлений 
![Снимок экрана от 2023-08-07 18-04-49](https://github.com/atls/common/assets/126339170/e015afe0-03b4-4c1f-ac96-40a394e4d100)

**Comment by sollidy** [comment]
сделай максимальный апгрейд, при котором не возникают ошибки, у тебя есть еще пакеты которые можно обновить

**Comment by LevKrestuaninov** [comment]
сейчас уже максимум, при дальнейшей установке yarn check не проходит, хотя yarn test unit проходит

**Comment by sollidy** [comment]
husky, pino?

**Comment by LevKrestuaninov** [comment]
да, работает, запушил

**Comment by LevKrestuaninov** [comment]
уже

**Comment by sollidy** [comment]
пр не вижу

**Comment by LevKrestuaninov** [comment]
пр?

**Comment by sollidy** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by sollidy** [comment]
сделай еще анализ по зависимостям, почему ошибки возникают, какие пакеты зависят от typescript, eslint, jest. Что бы ты предложил , чтобы исправить ошибки?

**Comment by LevKrestuaninov** [comment]
изменил вроде бы, вроде бы даже ничего не поломал

**Comment by LevKrestuaninov** [comment]
хорошо, проведу анализ

**Comment by sollidy** [comment]
вот зачем ты так сделал. теперь у тебя ветка смотрит не на последний коммит мастер ветки, хочешь сделать изменения, просто добавь новый коммит. Куда спешишь?

**Comment by TorinAsakura** [comment]
@LevKrestuaninov Дело не в 5 минутах, а в количестве хаоса на единицу времени, которое ты создаёшь

**Comment by TorinAsakura** [comment]
@LevKrestuaninov Ты сказал, что с гитом работать умеешь, а тут такое

**Comment by LevKrestuaninov** [comment]
ну так с историей я еще работал, это правда

**Comment by LevKrestuaninov** [comment]
@sollidy, кие дальнейшие действия?

**Comment by sollidy** [comment]
Тебе сейчас задание по git. В репозитории обновился yarn, соответственно твоя ветка отстоит от мастера (и не на один коммит): 
- откатить изменения которые ты наделал (читай git reflog, git reset)
- смержить все изменения из мастер ветки в свою ветку (git merge)

**Comment by LevKrestuaninov** [comment]
Да, изменения видел. Буду делать

**Comment by LevKrestuaninov** [comment]
### Сделал откат
@sollidy, Используя `git reset` перешел в самое начало, до обновления версии typeorm
![Снимок экрана от 2023-08-08 14-05-38](https://github.com/atls/common/assets/126339170/bbafc4da-ff22-47a6-882d-dd5063c6fdb9)

правильное ли сейчас положение? можно ли выполнять следующий пункт?

**Comment by sollidy** [comment]
похоже на то, доделывай. Как сделаешь push посмотрю

**Comment by LevKrestuaninov** [comment]
@sollidy, Мой план действий:
 
`git pull origin master` - копирование master в локальный репозиторий 

`git merge master` - (в ветке enhancement) слияние ветки enhancement с master
